### ISSUE TITLE
Error: Chunk format can't be selected by default when no target is specified

### ISSUE THREAD

**Issue by nimaeslamloo** [telenko/node-mf#1]
Getting `Error: Chunk format can't be selected by default when no target is specified` when setting target to false and use `NodeAsyncHttpRuntime` plugin

**Comment by telenko** [comment]
Hi @nimaeslamloo , thanks for raising this.
The issue happened after release of webpack@5.41.0. 
I will fix backward compatibility of my plugins soon, but while I'm working on it, you can fix it for your projects in 2 possible ways:
1) use webpack@5.40.0 and below
2) keep latest webpack, but add:
`output: { chunkFormat: "commonjs" } `
to the webpack config of 'node' build

**Comment by telenko** [comment]
Hi @nimaeslamloo , check out **0.0.5** version. Issue should be fixed.

**Comment by telenko** [comment]
Closing issue. Fixed by this [commit](https://github.com/telenko/node-mf/commit/896552a965f8d676ea0354619ddd2e37dd4b9179)
