### ISSUE TITLE
NodeAsyncHttpRuntime compatibility with NextJS

### ISSUE THREAD

**Issue by josselinbuils** [telenko/node-mf#2]
Hello,

First, thank you for you work, that is great 👏

Do you think `NodeAsyncHttpRuntime` could be made easily compatible with NextJS in case we want to use NextJS to both expose and consume modules that will be rendered on server side?

**Comment by telenko** [comment]
Hi @josselinbuils ,

I've tried using NodeAsyncHttpRuntime inside Next.js but it has failed to start. It will be one of the next steps to add support of NodeAsyncHttpRuntime into Next.js.

**Comment by noreiller** [comment]
Hello @telenko, I am a co-worker of @josselinbuils. Thanks for your work, it worked well with a regular webpack build (no Next.js). For Next.js, I had to fork it and I enchanced it a little bit to make it work.
I plan to open a PR to your repo soon.

**Comment by telenko** [comment]
Hi @noreiller. thanks! 
For now I don't have enough time for the library support, so any help is welcomed.

**Comment by noreiller** [comment]
Hello @telenko, for your information, I have forked the project and started to implement the NodeAsyncHttpRuntime compatibility with NextJS.

**Comment by telenko** [comment]
Hi Aurelien,

Sure, thanks for you work! Waiting for PR, let me know if you need some
help!

пн, 3 січ. 2022, 19:21 користувач Aurélien MANCA ***@***.***>
пише:

**Comment by noreiller** [comment]
Hello, as promised, here is the PR: https://github.com/telenko/node-mf/pull/10
